apiVersion: v1
kind: Service
metadata:
  name: spinnaker-svc
  namespace: spinnaker
  labels:
    app: spin
    stack: deck
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http1
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http2
  selector:
    load-balancer-spin-deck: "true"
  type: ClusterIP