apiVersion: v1
kind: ConfigMap

metadata:
  name: shopapi-cm

data:
  DB_HOST: terraform-20240929140715722500000001.csuabtqjbyud.us-east-1.rds.amazonaws.com
  DB_NAME: bookstore
  DB_USER: appuser
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "1"