# Devteds Course Materials. Find more at https://www.devteds.com/kubernetes-course-aws-eks-terraform


apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopapi
spec:
  selector:
    matchLabels:
      app: shopapi
  replicas: 1
  template:
    metadata:
      labels:
        app: shopapi
    spec:
      containers:
      - name: shopapi
        image: devteds/demo-bookstore-shopapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: shopapi-cm
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: shopapi-sec
                key: DB_PASSWORD


# Devteds Course Materials. Find more at https://www.devteds.com 
# K8S Course: https://www.devteds.com/kubernetes-course-aws-eks-terraform
# Course on Udemy: https://www.udemy.com/course/kubernetes-on-aws-eks-hands-on-guide-for-devs-devops