apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
 name: spinnaker-role
 namespace: default
rules:
- apiGroups: [""]
  resources: ["namespaces", "configmaps", "events", "replicationcontrollers", "serviceaccounts", "pods/logs"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["list", "get"]
- apiGroups: [“apps”]
  resources: [“controllerrevisions”, "statefulsets"]
  verbs: [“list”]
- apiGroups: ["extensions", "app"]
  resources: ["deployments", "replicasets", "ingresses"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: spinnaker-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spinnaker-role
subjects:
- namespace: default
  kind: ServiceAccount
  name: spinnaker-service-account
# ---
# apiVersion: v1
# kind: Config
# clusters:
#   — name: local
#   cluster:
#   server: https://kubernetes.default.svc.cluster.local:443
# users:
#   — name: local
#   user:
#   token: WlhsS2FHSkhZMmxQYVVwVFZYcEpNVTVwU1hOSmJsSTFZME5KTmtscmNGaFdRMG81TG1WNVNuQmpNMDFwVDJsS2NtUlhTbXhqYlRWc1pFZFdla3d6VG14amJscHdXVEpXYUZreVRuWmtWelV3U1dsM2FXRXpWbWxhV0VwMVdsaFNiR041TlhCaWVUbDZXbGhLTW1GWFRteFpWMDVxWWpOV2RXUkRPWFZaVnpGc1l6TkNhRmt5VldsUGFVcHJXbGRhYUdSWGVEQkphWGRwWVROV2FWcFlTblZhV0ZKc1kzazFjR0o1T1hwYVdFb3lZVmRPYkZsWFRtcGlNMVoxWkVNNWVscFhUbmxhV0ZGMVltMUdkRnBUU1RaSmJrNTNZVmMxZFZsWGRHeGphVEY2V2xoS01tRlhUbXhNVjBacVdUSTVNV0p1VVhSa1J6bHlXbGMwZEZscVRuaE5lazFwVEVOS2NtUlhTbXhqYlRWc1pFZFdla3h0YkhaTU0wNXNZMjVhY0ZreVZtaFpNazUyWkZjMU1Fd3pUbXhqYmxwd1dUSlZkRmxYVG1waU0xWjFaRU0xZFZsWE1XeEphbTlwWXpOQ2NHSnROV2hoTWxaNVRGaE9iR051V25CWk1sVjBXVmRPYW1JelZuVmtRMGx6U1cxME1WbHRWbmxpYlZZd1dsaE5kV0ZYT0haak1sWjVaRzFzYWxwWFJtcFpNamt4WW01UmRtTXlWbmxrYld4cVdsTXhhRmt5VG5aa1Z6VXdURzVXY0ZwRFNUWkpiVTB6VG1wcmQxcFhVWHBNVkVWNlRrZE5kRTFVUm14UFF6RnBUVmRLYkV4VVJYbGFSMVpwV21wV2FVMUhTbXRhVTBselNXNU9NVmxwU1RaSmJrNDFZek5TYkdKVWNIcGFXRW95WVZkT2JGbFhUbXBpTTFaMVpFUndhMXBYV21oa1YzZ3dUMjVPZDJGWE5YVlpWM1JzWTJreGVscFlTakpoVjA1c1RGZEdhbGt5T1RGaWJsRnBabEV1WkZCUVFqRnZTMUZMZERoeWJuQkxVa2ROWmpWaVozUmZUekl6TFV3M1p6ZG9lREJDU25FM1RqUmlaekJ5TkhsdVRVa3dXbUZpUm1neVp6SlVWVVpITWxWcVVYUlBNVXhhUTFCRVZqTkRiMGhLTjBweWVHMXNjemRpZFRGU2FqUnZXVXhaVTJSS1QxZ3dTRmh5UzAxeFJtMVFUREp3ZFhKUFZVZHJhVkpWVVZCNWEyWlNaVTlXZGxWclpFaFVia2d6UkZJd1ozSnlla3BoY1VwMFpFUkxUbTFPZUU5TFFtNHRhVEJVZFRkaFNXWkhjVVZWUmpOWE9ERm1UV1JxYm01cGNuQkNhMkpWVVdsWWNYRXpjR3BGVDNoRFFsVlFSR1pRTld3MWFDMWthemxMWlZWWmVqRjZXRUZSTlVGNlIxODJkMFZXU0MxSk5YaFljbFpOUVZGV09YVlhRbmxVU1hZd1RVTmZTRTFpU0ZKMlN6UjVjalk1VmtWTE0xVjZNMGswWTJOYU4wSjZlSEZ4WDB4R05UUnhPVU55WkZsSFdFNURVSFJqUlZKRlZtTXRRemRoWW05bVZHMTNOekJyTFhVeU5saGlTbEYzCg==
# contexts:
#   — name: local
#   context:
#   cluster: local
#   user: local
