apiVersion: v1
kind: Service
metadata:
  name: hello-go-service
spec:
  ports:
  - port: 31004
    # nodePort: 31004
    targetPort: hello-go-port
    protocol: TCP
  selector:
    app: hello-go
  type: ClusterIP
